version: '3.9'

services:
  db:
    image: postgres:14.3
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    container_name: web
    image: python:3.9
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: